"""Initial migration

Revision ID: 505c84041b35
Revises: 
Create Date: 2024-01-25 22:56:17.655289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505c84041b35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fio', sa.VARCHAR(length=100), nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('position', sa.VARCHAR(length=120), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('rank', sa.VARCHAR(length=120), nullable=True),
    sa.Column('education', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
